In [6]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%run FuzzyLogic.ipynb

#iris class, attr. and label read in from file
class Iris:
    def __init__(self, sl, sw, pl, pw, classifier):
        self.sl = sl
        self.sw = sw
        self.pl = pl
        self.pw = pw
        self.classifier = classifier

#read from file
def load_data():
    f=open("iris.data", "r")
    
    f1 = f.readlines()
    
    data = []
    
    for x in f1:
        x = x.strip("\n").split(',')
        if(len(x) == 5):
            data.append( Iris(x[0], x[1], x[2], x[3], x[4]) )
    
    return data

#print the data points to find mem. fun.
def print_atr(data):
    
    size = len(data)
    
    pl = np.zeros(size)
    pw = np.zeros(size)
    sl = np.zeros(size)
    sw = np.zeros(size)
    
    for i in range(size):
        pl[i] = data[i].pl
        pw[i] = data[i].pw
        sl[i] = data[i].sl
        sw[i] = data[i].sw
    
    y = np.arange(50)
    
    
    plt.plot(pl[0:50],y, 'o', color='red', label="Iris Setosa");
    plt.plot(pl[50:100],y, 'o', color='green', label="Iris Versicolour");
    plt.plot(pl[100:150],y, 'o', color='blue', label="Iris Virginica");
    plt.legend()
    plt.title("Petal Length")
    plt.show()
    print("Min Iris Setosa: ", np.amin(pl[0:50]))
    print("Max Iris Setosa: ", np.amax(pl[0:50]))
    
    print("Min Iris Versicolour: ", np.amin(pl[50:100]))
    print("Max Iris Versicolour: ", np.amax(pl[50:100]))
    
    print("Min Iris Virginica: ", np.amin(pl[100:150]))
    print("Max Iris Virginica: ", np.amax(pl[100:150]))
    
    
    plt.plot(pw[0:50],y, 'o', color='red', label="Iris Setosa");
    plt.plot(pw[50:100],y, 'o', color='green', label="Iris Versicolour");
    plt.plot(pw[100:150],y, 'o', color='blue', label="Iris Virginica");
    plt.legend()
    plt.title("Petal Width")
    plt.show()
    print("Min Iris Setosa: ", np.amin(pw[0:50]))
    print("Max Iris Setosa: ", np.amax(pw[0:50]))
    
    print("Min Iris Versicolour: ", np.amin(pw[50:100]))
    print("Max Iris Versicolour: ", np.amax(pw[50:100]))
    
    print("Min Iris Virginica: ", np.amin(pw[100:150]))
    print("Max Iris Virginica: ", np.amax(pw[100:150]))
    
    plt.plot(sw[0:50],y, 'o', color='red', label="Iris Setosa");
    plt.plot(sw[50:100],y, 'o', color='green', label="Iris Versicolour");
    plt.plot(sw[100:150],y, 'o', color='blue', label="Iris Virginica");
    plt.legend()
    plt.title("Sepal Width")
    plt.show()
    print("Min Iris Setosa: ", np.amin(sw[0:50]))
    print("Max Iris Setosa: ", np.amax(sw[0:50]))
    
    print("Min Iris Versicolour: ", np.amin(sw[50:100]))
    print("Max Iris Versicolour: ", np.amax(sw[50:100]))
    
    print("Min Iris Virginica: ", np.amin(sw[100:150]))
    print("Max Iris Virginica: ", np.amax(sw[100:150]))
    
    plt.plot(sl[0:50],y, 'o', color='red', label="Iris Setosa");
    plt.plot(sl[50:100],y, 'o', color='green', label="Iris Versicolour");
    plt.plot(sl[100:150],y, 'o', color='blue', label="Iris Virginica");
    plt.legend()
    plt.title("Sepal Length")
    plt.show()
    print("Min Iris Setosa: ", np.amin(sl[0:50]))
    print("Max Iris Setosa: ", np.amax(sl[0:50]))
    
    print("Min Iris Versicolour: ", np.amin(sl[50:100]))
    print("Max Iris Versicolour: ", np.amax(sl[50:100]))
    
    print("Min Iris Virginica: ", np.amin(sl[100:150]))
    print("Max Iris Virginica: ", np.amax(sl[100:150]))

#create the mem fns using the fn from fuzzy logic file
def create_ant_mem_fns():
    X = np.arange(start=0.0, stop=9.0, step=0.1)
    
    ants = []
    
    SSL = make_trap_membership_fn_float(X,3.8,4.6,5.2,6.0)
    MSL = make_trap_membership_fn_float(X,4.5,5.5,6.0,8.0)
    LSL = make_trap_membership_fn_float(X,5.0,6.3,8.9,8.9)
    
    ants.append(SSL)
    ants.append(MSL)
    ants.append(LSL)
    
#     SSW = make_trap_membership_fn_float(X,1.8,2.2,2.7,3.2)
#     MSW = make_trap_membership_fn_float(X,2,2.5,3.4,4)
#     LSW = make_trap_membership_fn_float(X,2,3,4,5)
    
#     ants.append(SSW)
#     ants.append(MSW)
#     ants.append(LSW)
    
    SPL = make_trap_membership_fn_float(X,0,1,2,3)
    MPL = make_trap_membership_fn_float(X,2,3.0,4.8,6.1)
    LPL = make_trap_membership_fn_float(X,3.8,5.2,8,8)
    
    ants.append(SPL)
    ants.append(MPL)
    ants.append(LPL)
    
    SPW = make_trap_membership_fn_float(X,0.0,0.0,0.6,1.0)
    MPW = make_trap_membership_fn_float(X,0.5,1.0,1.4,2.5)
    LPW = make_trap_membership_fn_float(X,1.1,1.8,3.0,3.3)
    
    ants.append(SPW)
    ants.append(MPW)
    ants.append(LPW)
    
    return ants

#graphical rep
def print_mem_fns(mem_fns, title, names):
    for i in range(len(mem_fns)):
        plt.plot(mem_fns[i], label=names[i]);
    plt.legend()
    plt.title(title)
    plt.xticks(np.arange(len(mem_fns[0]), step=10), ["0.0", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0"])

    plt.show()

# create mem. conseqeunts of rules using trapezoidal fn from fuzzy logic file
def create_cons():
    X = np.arange(start=0.0, stop=10.0)
    
    cons = []
    
    IS = make_trap_membership_fn(X,0,2,2,4)
    IVC = make_trap_membership_fn(X,3,5,5,7)
    IVG = make_trap_membership_fn(X,6,8,8,10)
    
    
    cons.append(IS)
    cons.append(IVC)
    cons.append(IVG)
    
    return cons

# create rules for usage in gen. system
def create_rules():
    rules = []
    
#     rule = Rule(np.array([0,5,6,9]),0)
#     rules.append(rule)
    
#     rule = Rule(np.array([1,3,7,10]),1)
#     rules.append(rule)
    
#     rule = Rule(np.array([2,4,8,11]),2)
#     rules.append(rule)

    rule = Rule(np.array([0,3,6]),0)
    rules.append(rule)
    
    rule = Rule(np.array([1,4,7]),1)
    rules.append(rule)
    
    rule = Rule(np.array([2,5,8]),2)
    rules.append(rule)
    
    return rules

#get the classified label
def getClass(o):
    
    if(o==0):
        return "Iris-setosa"
    if(o==1):
        return "Iris-versicolor"
    if(o==2):
        return "Iris-virginica"
#classify one iris 
def start(one, two, three):
    amf = create_ant_mem_fns()
    cmf = create_cons()
    rules = create_rules()
    imp_op = "cm"
    inputs = np.zeros(3)
    inputs[0] = one
    inputs[1] = two
    inputs[2] = three
    
    res = generalized_fuzzy_logic_f(rules, amf, cmf, imp_op, inputs)
        
    classi = getClass(res)
    return classi
#start process of classification of 150 iris
def test():
    data = load_data()
    good = 0
    bad = 0
    cm = np.zeros((3,3))
    
    for i in range(len(data)):
        classifier = start(data[i].sl,data[i].pl, data[i].pw)
        if(classifier!=data[i].classifier):
            if(data[i].classifier == "Iris-setosa" and classifier == "Iris-versicolor"):
                cm[0][1] = cm[0][1] + 1
            if(data[i].classifier == "Iris-setosa" and classifier == "Iris-virginica"):
                cm[0][2] = cm[0][2] + 1
            if(data[i].classifier == "Iris-versicolor" and classifier == "Iris-setosa"):
                cm[1][0] = cm[1][0] + 1
            if(data[i].classifier == "Iris-versicolor" and classifier == "Iris-virginica"):
                cm[1][2] = cm[1][2] + 1
            if(data[i].classifier == "Iris-virginica" and classifier == "Iris-setosa"):
                cm[2][0] = cm[2][0] + 1
            if(data[i].classifier == "Iris-virginica" and classifier == "Iris-versicolor"):
                cm[2][1] = cm[2][1] + 1
                
            bad = bad+1
        else:
            good=good+1
            if(classifier == "Iris-setosa"):
                cm[0][0] = cm[0][0] + 1
            if(classifier == "Iris-versicolor"):
                cm[1][1] = cm[1][1] + 1
            if(classifier == "Iris-virginica"):
                cm[2][2] = cm[2][2] + 1
    print(cm)
            
    return (good/(bad+good))
#graphical rep.
def print_all_mem():
    a = create_ant_mem_fns() 

    names = []

    names.append("SMALL")
    names.append("MEDIUM")
    names.append("LARGE")

    print_mem_fns(a[0:3], "Sepal Length", names)
#     print_mem_fns(a[3:6], "Sepal Width", names)
    print_mem_fns(a[3:6], "Petal Length", names)
    print_mem_fns(a[6:9], "Petal Width", names)
# put mem fns on iris data to vis.  
def overlay_on_data(mem_fns, names, data, attr):
    size = len(data)
    
    pl = np.zeros(size)
    pw = np.zeros(size)
    sl = np.zeros(size)
    
    for i in range(size):
        pl[i] = float(data[i].pl) * 10
        pw[i] = float(data[i].pw) * 10 
        sl[i] = float(data[i].sl) * 10
    
    y = np.arange(50)
    
    if(attr == "pw"):
        for i in range(len(mem_fns)):
            plt.plot(mem_fns[i]*50, label=names[i]);
        
        plt.plot(pw[0:50],y, 'o', color='red', label="Iris Setosa");
        plt.plot(pw[50:100],y, 'o', color='green', label="Iris Versicolour");
        plt.plot(pw[100:150],y, 'o', color='blue', label="Iris Virginica");
        plt.legend()
        plt.title("Petal Width")
        plt.xticks(np.arange(len(mem_fns[0]), step=10), ["0.0", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0"])
        plt.show()
    elif(attr == "pl"):
        for i in range(len(mem_fns)):
            plt.plot(mem_fns[i]*50, label=names[i]);
            
        plt.plot(pl[0:50],y, 'o', color='red', label="Iris Setosa");
        plt.plot(pl[50:100],y, 'o', color='green', label="Iris Versicolour");
        plt.plot(pl[100:150],y, 'o', color='blue', label="Iris Virginica");
        plt.legend()
        plt.title("Petal Length")
        plt.xticks(np.arange(len(mem_fns[0]), step=10), ["0.0", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0"])
        plt.show()
    elif(attr == "sl"):
        for i in range(len(mem_fns)):
            plt.plot(mem_fns[i]*50, label=names[i]);
            
        plt.plot(sl[0:50],y, 'o', color='red', label="Iris Setosa");
        plt.plot(sl[50:100],y, 'o', color='green', label="Iris Versicolour");
        plt.plot(sl[100:150],y, 'o', color='blue', label="Iris Virginica");
        plt.legend()
        plt.title("Sepal Length")
        plt.xticks(np.arange(len(mem_fns[0]), step=10), ["0.0", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0"])
        plt.show()
#grph. rep.
def print_all_overlay():
    a = create_ant_mem_fns() 

    names = []

    names.append("SMALL")
    names.append("MEDIUM")
    names.append("LARGE")
    
    data = load_data()

    overlay_on_data(a[0:3], names, data, "sl")
    overlay_on_data(a[3:6], names, data, "pl")
    overlay_on_data(a[6:9], names, data, "pw")
    
# print_all_mem()
# print_atr(load_data())

# print_all_overlay()

a = test()
print("ACC")
print(a)







[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]
ACC
0.96
